require("mini.cursorword").setup({})
require("mini.comment").setup({})
require("mini.jump").setup({})
require("mini.jump2d").setup({})
require("mini.surround").setup()
require("mini.tabline").setup({})

require("config.mini.base16")
require("config.mini.starter")
require("config.mini.statusline")
